# Generated by Django 2.2.1 on 2019-07-13 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Ponencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ponencia', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha_ponencia', models.DateTimeField(verbose_name='Fecha')),
                ('duracion', models.DurationField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Ponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ponente', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_ponente', models.CharField(max_length=50, verbose_name='Apellido')),
                ('cargo', models.CharField(max_length=50)),
                ('organizacion_ponente', models.CharField(max_length=65, verbose_name='Organización a la que pertenece')),
                ('ponencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eventos.Ponencia')),
            ],
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateField(verbose_name='Fecha')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asistente', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_asistente', models.CharField(max_length=50, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=70)),
                ('organizacion_asistente', models.CharField(max_length=65, verbose_name='Organización a la que pertenece')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
            ],
        ),
    ]
