# Generated by Django 2.2.1 on 2019-07-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponencia',
            name='duracion',
            field=models.CharField(max_length=9),
        ),
    ]
